name: Fern The Frenchie
favicon: null
layout_spectrum: 0.97078
typography_spectrum: 0.48704
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#160702'
    - '#feb859'
    - '#b15411'
    - '#87380f'
    - '#fe6623'
  brandStrength: 0.25
  lightness: 0.5912287752144039
  saturation: 0.5588697521016002
  rhythmicContrast: 0.25
purpose: []
