favicon: null
name: Fern The Frenchie
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.3870968
  brandStrength: 0.6792115
  rhythmicContrast: 0.6379929
  brandColors:
    - '#0F0B0E'
    - '#CFC7C5'
    - '#383130'
    - '#A39B99'
    - '#884C4B'
  lightness: 0.8602151
typography_spectrum: 0.48704
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.1003584
analytics:
  twitter: null
  google: null
  facebook: null
